name: Docker Image CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3.3.0

      - name: Docker Login
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # - name: Go Build Cache for Docker
      #   uses: actions/cache@v4.0.2
      #   with:
      #     path: go-build-cache
      #     key: ${{ runner.os }}-go-build-cache-${{ hashFiles('**/go.sum') }}

      # - name:
      #     inject go-build-cache into docker
      #     # v1 was composed of two actions: "inject" and "extract".
      #     # v2 is unified to a single action.
      #   uses: reproducible-containers/buildkit-cache-dance@v2.1.2
      #   with:
      #     cache-source: go-build-cache

      - name: Build
        uses: docker/build-push-action@v5.3.0
        with:
          # cache-from: type=gha
          # cache-to: type=gha,mode=max
          # Path to the Dockerfile
          file: Dockerfile.vendor
          # platforms: linux/amd64,linux/arm64
          # List of tags
          tags: wushie/test:latest, wushie/test:${{ github.run_number }}
          push: true # optional, default is false
