name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.3
      
    - name: Build and push Docker images
      uses: docker/build-push-action@v5.3.0
      with:
        # Path to the Dockerfile
        file: Dockerfile.default
        # List of tags
        tags: wushie/test:latest, wushie/test:${{ github.run_number }}
