name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /var/lib/docker
        key: ${{ runner.os }}-docker-${{ hashFiles('**/Dockerfile*') }}
        restore-keys: |
          ${{ runner.os }}-docker-
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile.default --tag test:$(date +%s)
      
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      
    - name: Push Docker image to Docker Hub
      run: docker push your_image_name:latest
