name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    - name: Docker Login
      uses: docker/login-action@v3.1.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
    - name: Build
      uses: docker/build-push-action@v5.3.0
      with:
        # Path to the Dockerfile
        file: Dockerfile.default
        # List of tags
        tags: wushie/test:latest, wushie/test:${{ github.run_number }}
        push: true # optional, default is false
